# Generated by Django 4.2.16 on 2024-10-09 19:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatDetails',
            fields=[
                ('thread_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.TextField()),
                ('chatName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DjWrite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thread_id', models.TextField()),
                ('thread_ts', models.TextField()),
                ('task_id', models.TextField()),
                ('idx', models.IntegerField()),
                ('channel', models.TextField()),
                ('value', models.BinaryField(blank=True, default=None, null=True)),
            ],
            options={
                'unique_together': {('thread_id', 'thread_ts', 'task_id', 'idx')},
            },
        ),
        migrations.CreateModel(
            name='DjCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_ts', models.TextField()),
                ('parent_ts', models.TextField(blank=True, default=None, null=True)),
                ('checkpoint', models.BinaryField()),
                ('metadata', models.BinaryField()),
                ('thread_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talkpdf.chatdetails')),
            ],
            options={
                'unique_together': {('thread_id', 'thread_ts')},
            },
        ),
    ]
