# Generated by Django 4.2.16 on 2024-10-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkpdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatdetails',
            name='thread_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
