# Generated by Django 4.2.16 on 2024-09-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkpdf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTalkPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
