# Generated by Django 4.2.16 on 2024-10-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkpdf', '0002_alter_chatdetails_thread_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatdetails',
            name='thread_id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
