# Generated by Django 4.2.16 on 2024-10-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkpdf', '0002_alter_djwrite_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djcheckpoint',
            name='thread_id',
            field=models.TextField(),
        ),
    ]
