# Generated by Django 4.2.16 on 2024-10-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkpdf', '0003_alter_djcheckpoint_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatdetails',
            name='user_id',
            field=models.TextField(default='default_user'),
        ),
    ]
