# Generated by Django 4.2.16 on 2024-09-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talkpdf', '0003_alter_messagetalkpdf_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPdf',
        ),
    ]
