# Generated by Django 4.2.16 on 2024-10-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkpdf', '0004_chatdetails_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatdetails',
            name='user_id',
            field=models.TextField(),
        ),
    ]
