# Generated by Django 4.2.16 on 2024-10-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkpdf', '0004_delete_userpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrionTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('userInput', models.TextField()),
                ('orionOutput', models.TextField()),
                ('model_name', models.TextField()),
                ('inputTokens', models.IntegerField()),
                ('outputTokens', models.IntegerField()),
                ('totalTokes', models.IntegerField()),
            ],
        ),
    ]
