# Generated by Django 4.2.16 on 2024-10-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkpdf', '0005_oriontalk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGraph',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('graph_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DjWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.TextField()),
                ('thread_ts', models.TextField()),
                ('task_id', models.TextField()),
                ('idx', models.IntegerField()),
                ('channel', models.TextField()),
                ('value', models.BinaryField(blank=True, default=None, null=True)),
            ],
            options={
                'unique_together': {('thread_id', 'thread_ts', 'task_id', 'idx')},
            },
        ),
        migrations.CreateModel(
            name='DjCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.TextField()),
                ('thread_ts', models.TextField()),
                ('parent_ts', models.TextField(blank=True, default=None, null=True)),
                ('checkpoint', models.BinaryField()),
                ('metadata', models.BinaryField()),
            ],
            options={
                'unique_together': {('thread_id', 'thread_ts')},
            },
        ),
    ]
