# Generated by Django 4.2.16 on 2024-11-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkpdf', '0005_alter_djcheckpoint_checkpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djcheckpoint',
            name='checkpoint',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='djcheckpoint',
            name='metadata',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='djwrite',
            name='value',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
