# Generated by Django 4.2.16 on 2024-10-17 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talkpdf', '0005_alter_chatdetails_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatdetails',
            name='user_id',
        ),
        migrations.AddField(
            model_name='chatdetails',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
