# Generated by Django 4.2.16 on 2024-10-08 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talkpdf', '0006_chatgraph_djwrite_djcheckpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.TextField()),
                ('chatName', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ChatGraph',
        ),
        migrations.DeleteModel(
            name='MessageTalkPdf',
        ),
        migrations.DeleteModel(
            name='OrionTalk',
        ),
        migrations.RemoveField(
            model_name='djcheckpoint',
            name='id',
        ),
        migrations.AlterField(
            model_name='djcheckpoint',
            name='thread_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='chatdetails',
            name='thread_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talkpdf.djcheckpoint'),
        ),
    ]
