# Generated by Django 4.2.16 on 2024-11-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talkpdf', '0006_alter_djcheckpoint_checkpoint_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DjCheckpoint',
            new_name='ChatCheckpoint',
        ),
        migrations.RenameModel(
            old_name='DjWrite',
            new_name='ChatWrite',
        ),
    ]
