# Generated by Django 4.2.16 on 2024-10-08 15:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('talkpdf', '0007_chatdetails_delete_chatgraph_delete_messagetalkpdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='djcheckpoint',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatdetails',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatdetails',
            name='thread_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='djcheckpoint',
            name='thread_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='djwrite',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
