# Generated by Django 4.2.16 on 2024-11-26 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talkpdf', '0008_chatdetails_file_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatdetails',
            old_name='chatName',
            new_name='chat_name',
        ),
    ]
